version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/Source/DashboardTabApp"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/Source/QuestionsTabApp"
    schedule:
      interval: "daily"
